@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "cncs.academy.ess.controller.TodoListController#getAllTodoLists(Context)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "cncs.academy.ess.controller.TodoListController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1179509012 { 
   	label=academy
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1149713283 { 
   	label=ess
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1220534068 { 
   	label=TodoListController
	labeljust=l
	fillcolor=white
	style=filled
   
   TodoListController684083174XXXgetAllTodoLists1678783089[
	label="+ getAllTodoLists()"
	style=filled
	fillcolor=white
	tooltip="TodoListController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_685580547 { 
   	label=TodoListsService
	labeljust=l
	fillcolor=white
	style=filled
   
   TodoListsService910619383XXXgetAllTodoLists104431[
	label="+ getAllTodoLists()"
	style=filled
	fillcolor=white
	tooltip="TodoListsService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_866804620 { 
   	label=InMemoryTodoListsRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   InMemoryTodoListsRepository997760537XXXfindAllByUserId104431[
	label="+ findAllByUserId()"
	style=filled
	fillcolor=white
	tooltip="InMemoryTodoListsRepository

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
TodoListController684083174XXXgetAllTodoLists1678783089 -> TodoListsService910619383XXXgetAllTodoLists104431;
TodoListsService910619383XXXgetAllTodoLists104431 -> InMemoryTodoListsRepository997760537XXXfindAllByUserId104431;
    
}
@enduml